/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CaseBase model module.
 * @module model/CaseBase
 * @version 1.0.11
 */
export class CaseBase {
  /**
   * Constructs a new <code>CaseBase</code>.
   * @alias module:model/CaseBase
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CaseBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseBase} obj Optional instance to populate.
   * @return {module:model/CaseBase} The populated <code>CaseBase</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseBase();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CaseBase.prototype.name = undefined;

