/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DocumentStatus.
 * @enum {String}
 * @readonly
 */
const DocumentStatus = {
  /**
   * value: "Active"
   * @const
   */
  active: "Active",

  /**
   * value: "Inactive"
   * @const
   */
  inactive: "Inactive",

  /**
   * Returns a <code>DocumentStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DocumentStatus} The enum <code>DocumentStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DocumentStatus};