/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The ActionParameterInfo model module.
 * @module model/ActionParameterInfo
 * @version 1
 */
export class ActionParameterInfo {
  /**
   * Constructs a new <code>ActionParameterInfo</code>.
   * Action parameter info
   * @alias module:model/ActionParameterInfo
   * @class
   * @param name {String} The action parameter name
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>ActionParameterInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActionParameterInfo} obj Optional instance to populate.
   * @return {module:model/ActionParameterInfo} The populated <code>ActionParameterInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ActionParameterInfo();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('valueTypes'))
        obj.valueTypes = ApiClient.convertToType(data['valueTypes'], ['String']);
      if (data.hasOwnProperty('valueSources'))
        obj.valueSources = ApiClient.convertToType(data['valueSources'], ['String']);
      if (data.hasOwnProperty('valueReferences'))
        obj.valueReferences = ApiClient.convertToType(data['valueReferences'], ['String']);
    }
    return obj;
  }
}

/**
 * The action parameter name
 * @member {String} name
 */
ActionParameterInfo.prototype.name = undefined;

/**
 * The action parameter description
 * @member {String} description
 */
ActionParameterInfo.prototype.description = undefined;

/**
 * The action parameter types
 * @member {Array.<String>} valueTypes
 */
ActionParameterInfo.prototype.valueTypes = undefined;

/**
 * The action parameter source types
 * @member {Array.<String>} valueSources
 */
ActionParameterInfo.prototype.valueSources = undefined;

/**
 * The action parameter reference types
 * @member {Array.<String>} valueReferences
 */
ActionParameterInfo.prototype.valueReferences = undefined;

