/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The ActionIssueInfo model module.
 * @module model/ActionIssueInfo
 * @version 1
 */
export class ActionIssueInfo {
  /**
   * Constructs a new <code>ActionIssueInfo</code>.
   * Action issue info
   * @alias module:model/ActionIssueInfo
   * @class
   * @param name {String} The action name
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>ActionIssueInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActionIssueInfo} obj Optional instance to populate.
   * @return {module:model/ActionIssueInfo} The populated <code>ActionIssueInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ActionIssueInfo();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('parameterCount'))
        obj.parameterCount = ApiClient.convertToType(data['parameterCount'], 'Number');
    }
    return obj;
  }
}

/**
 * The action name
 * @member {String} name
 */
ActionIssueInfo.prototype.name = undefined;

/**
 * The action issue message
 * @member {String} message
 */
ActionIssueInfo.prototype.message = undefined;

/**
 * The action issue description
 * @member {Number} parameterCount
 */
ActionIssueInfo.prototype.parameterCount = undefined;

