/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * Enum class CaseFieldDateType.
 * @enum {String}
 * @readonly
 */
const CaseFieldDateType = {
  /**
   * value: "Day"
   * @const
   */
  day: "Day",

  /**
   * value: "Sunday"
   * @const
   */
  sunday: "Sunday",

  /**
   * value: "Monday"
   * @const
   */
  monday: "Monday",

  /**
   * value: "Tuesday"
   * @const
   */
  tuesday: "Tuesday",

  /**
   * value: "Wednesday"
   * @const
   */
  wednesday: "Wednesday",

  /**
   * value: "Thursday"
   * @const
   */
  thursday: "Thursday",

  /**
   * value: "Friday"
   * @const
   */
  friday: "Friday",

  /**
   * value: "Saturday"
   * @const
   */
  saturday: "Saturday",

  /**
   * value: "Month"
   * @const
   */
  month: "Month",

  /**
   * value: "January"
   * @const
   */
  january: "January",

  /**
   * value: "February"
   * @const
   */
  february: "February",

  /**
   * value: "March"
   * @const
   */
  march: "March",

  /**
   * value: "April"
   * @const
   */
  april: "April",

  /**
   * value: "May"
   * @const
   */
  may: "May",

  /**
   * value: "June"
   * @const
   */
  june: "June",

  /**
   * value: "July"
   * @const
   */
  july: "July",

  /**
   * value: "August"
   * @const
   */
  august: "August",

  /**
   * value: "September"
   * @const
   */
  september: "September",

  /**
   * value: "October"
   * @const
   */
  october: "October",

  /**
   * value: "November"
   * @const
   */
  november: "November",

  /**
   * value: "December"
   * @const
   */
  december: "December",

  /**
   * value: "Year"
   * @const
   */
  year: "Year",

  /**
   * Returns a <code>CaseFieldDateType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/CaseFieldDateType} The enum <code>CaseFieldDateType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {CaseFieldDateType};