/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {CaseCancellationType} from './CaseCancellationType';
import {CaseFieldReference} from './CaseFieldReference';
import {CaseFieldSet} from './CaseFieldSet';
import {CaseSlot} from './CaseSlot';
import {CaseType} from './CaseType';
import {ObjectStatus} from './ObjectStatus';
import {OverrideType} from './OverrideType';

/**
 * The CaseSet model module.
 * @module model/CaseSet
 * @version 1
 */
export class CaseSet {
  /**
   * Constructs a new <code>CaseSet</code>.
   * The payroll case object, including case fields and related cases
   * @alias module:model/CaseSet
   * @class
   * @param caseType {module:model/CaseType} 
   * @param name {String} The case name (immutable)
   */
  constructor(caseType, name) {
    this.caseType = caseType;
    this.name = name;
  }

  /**
   * Constructs a <code>CaseSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseSet} obj Optional instance to populate.
   * @return {module:model/CaseSet} The populated <code>CaseSet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseSet();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('caseType'))
        obj.caseType = CaseType.constructFromObject(data['caseType']);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nameLocalizations'))
        obj.nameLocalizations = ApiClient.convertToType(data['nameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('nameSynonyms'))
        obj.nameSynonyms = ApiClient.convertToType(data['nameSynonyms'], ['String']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('descriptionLocalizations'))
        obj.descriptionLocalizations = ApiClient.convertToType(data['descriptionLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('defaultReason'))
        obj.defaultReason = ApiClient.convertToType(data['defaultReason'], 'String');
      if (data.hasOwnProperty('defaultReasonLocalizations'))
        obj.defaultReasonLocalizations = ApiClient.convertToType(data['defaultReasonLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('baseCase'))
        obj.baseCase = ApiClient.convertToType(data['baseCase'], 'String');
      if (data.hasOwnProperty('baseCaseFields'))
        obj.baseCaseFields = ApiClient.convertToType(data['baseCaseFields'], [CaseFieldReference]);
      if (data.hasOwnProperty('overrideType'))
        obj.overrideType = OverrideType.constructFromObject(data['overrideType']);
      if (data.hasOwnProperty('cancellationType'))
        obj.cancellationType = CaseCancellationType.constructFromObject(data['cancellationType']);
      if (data.hasOwnProperty('availableExpression'))
        obj.availableExpression = ApiClient.convertToType(data['availableExpression'], 'String');
      if (data.hasOwnProperty('buildExpression'))
        obj.buildExpression = ApiClient.convertToType(data['buildExpression'], 'String');
      if (data.hasOwnProperty('validateExpression'))
        obj.validateExpression = ApiClient.convertToType(data['validateExpression'], 'String');
      if (data.hasOwnProperty('lookups'))
        obj.lookups = ApiClient.convertToType(data['lookups'], ['String']);
      if (data.hasOwnProperty('slots'))
        obj.slots = ApiClient.convertToType(data['slots'], [CaseSlot]);
      if (data.hasOwnProperty('availableActions'))
        obj.availableActions = ApiClient.convertToType(data['availableActions'], ['String']);
      if (data.hasOwnProperty('buildActions'))
        obj.buildActions = ApiClient.convertToType(data['buildActions'], ['String']);
      if (data.hasOwnProperty('validateActions'))
        obj.validateActions = ApiClient.convertToType(data['validateActions'], ['String']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
      if (data.hasOwnProperty('clusters'))
        obj.clusters = ApiClient.convertToType(data['clusters'], ['String']);
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('caseSlot'))
        obj.caseSlot = ApiClient.convertToType(data['caseSlot'], 'String');
      if (data.hasOwnProperty('caseSlotLocalizations'))
        obj.caseSlotLocalizations = ApiClient.convertToType(data['caseSlotLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('cancellationDate'))
        obj.cancellationDate = ApiClient.convertToType(data['cancellationDate'], 'Date');
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [CaseFieldSet]);
      if (data.hasOwnProperty('relatedCases'))
        obj.relatedCases = ApiClient.convertToType(data['relatedCases'], [CaseSet]);
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
CaseSet.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
CaseSet.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
CaseSet.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
CaseSet.prototype.updated = undefined;

/**
 * @member {module:model/CaseType} caseType
 */
CaseSet.prototype.caseType = undefined;

/**
 * The case name (immutable)
 * @member {String} name
 */
CaseSet.prototype.name = undefined;

/**
 * The localized case names
 * @member {Object.<String, String>} nameLocalizations
 */
CaseSet.prototype.nameLocalizations = undefined;

/**
 * Synonyms for the case name
 * @member {Array.<String>} nameSynonyms
 */
CaseSet.prototype.nameSynonyms = undefined;

/**
 * The case description
 * @member {String} description
 */
CaseSet.prototype.description = undefined;

/**
 * The localized case descriptions
 * @member {Object.<String, String>} descriptionLocalizations
 */
CaseSet.prototype.descriptionLocalizations = undefined;

/**
 * The default case change reason
 * @member {String} defaultReason
 */
CaseSet.prototype.defaultReason = undefined;

/**
 * The localized default case change reasons
 * @member {Object.<String, String>} defaultReasonLocalizations
 */
CaseSet.prototype.defaultReasonLocalizations = undefined;

/**
 * The base case name
 * @member {String} baseCase
 */
CaseSet.prototype.baseCase = undefined;

/**
 * The base case fields
 * @member {Array.<module:model/CaseFieldReference>} baseCaseFields
 */
CaseSet.prototype.baseCaseFields = undefined;

/**
 * @member {module:model/OverrideType} overrideType
 */
CaseSet.prototype.overrideType = undefined;

/**
 * @member {module:model/CaseCancellationType} cancellationType
 */
CaseSet.prototype.cancellationType = undefined;

/**
 * The expression used to build a case
 * @member {String} availableExpression
 */
CaseSet.prototype.availableExpression = undefined;

/**
 * The expression used to build a case
 * @member {String} buildExpression
 */
CaseSet.prototype.buildExpression = undefined;

/**
 * The case validate expression
 * @member {String} validateExpression
 */
CaseSet.prototype.validateExpression = undefined;

/**
 * The case lookups
 * @member {Array.<String>} lookups
 */
CaseSet.prototype.lookups = undefined;

/**
 * The case slots
 * @member {Array.<module:model/CaseSlot>} slots
 */
CaseSet.prototype.slots = undefined;

/**
 * The case available actions
 * @member {Array.<String>} availableActions
 */
CaseSet.prototype.availableActions = undefined;

/**
 * The case build actions
 * @member {Array.<String>} buildActions
 */
CaseSet.prototype.buildActions = undefined;

/**
 * The case validate actions
 * @member {Array.<String>} validateActions
 */
CaseSet.prototype.validateActions = undefined;

/**
 * Custom attributes
 * @member {Object.<String, Object>} attributes
 */
CaseSet.prototype.attributes = undefined;

/**
 * The case clusters
 * @member {Array.<String>} clusters
 */
CaseSet.prototype.clusters = undefined;

/**
 * The case display name
 * @member {String} displayName
 */
CaseSet.prototype.displayName = undefined;

/**
 * The case slot
 * @member {String} caseSlot
 */
CaseSet.prototype.caseSlot = undefined;

/**
 * The localized case slots
 * @member {Object.<String, String>} caseSlotLocalizations
 */
CaseSet.prototype.caseSlotLocalizations = undefined;

/**
 * Cancellation date
 * @member {Date} cancellationDate
 */
CaseSet.prototype.cancellationDate = undefined;

/**
 * Derived case fields
 * @member {Array.<module:model/CaseFieldSet>} fields
 */
CaseSet.prototype.fields = undefined;

/**
 * Related cases
 * @member {Array.<module:model/CaseSet>} relatedCases
 */
CaseSet.prototype.relatedCases = undefined;

