/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {ObjectStatus} from './ObjectStatus';

/**
 * The CaseDocument model module.
 * @module model/CaseDocument
 * @version 1
 */
export class CaseDocument {
  /**
   * Constructs a new <code>CaseDocument</code>.
   * The case document API object
   * @alias module:model/CaseDocument
   * @class
   * @param name {String} The document name
   * @param content {String} The document content
   * @param contentType {String} The document content type
   */
  constructor(name, content, contentType) {
    this.name = name;
    this.content = content;
    this.contentType = contentType;
  }

  /**
   * Constructs a <code>CaseDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseDocument} obj Optional instance to populate.
   * @return {module:model/CaseDocument} The populated <code>CaseDocument</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseDocument();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('contentType'))
        obj.contentType = ApiClient.convertToType(data['contentType'], 'String');
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
CaseDocument.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
CaseDocument.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
CaseDocument.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
CaseDocument.prototype.updated = undefined;

/**
 * The document name
 * @member {String} name
 */
CaseDocument.prototype.name = undefined;

/**
 * The document content
 * @member {String} content
 */
CaseDocument.prototype.content = undefined;

/**
 * The document content type
 * @member {String} contentType
 */
CaseDocument.prototype.contentType = undefined;

