/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The CaseRelationReference model module.
 * @module model/CaseRelationReference
 * @version 1
 */
export class CaseRelationReference {
  /**
   * Constructs a new <code>CaseRelationReference</code>.
   * Case relation reference
   * @alias module:model/CaseRelationReference
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CaseRelationReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseRelationReference} obj Optional instance to populate.
   * @return {module:model/CaseRelationReference} The populated <code>CaseRelationReference</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseRelationReference();
      if (data.hasOwnProperty('sourceCaseName'))
        obj.sourceCaseName = ApiClient.convertToType(data['sourceCaseName'], 'String');
      if (data.hasOwnProperty('sourceCaseSlot'))
        obj.sourceCaseSlot = ApiClient.convertToType(data['sourceCaseSlot'], 'String');
      if (data.hasOwnProperty('targetCaseName'))
        obj.targetCaseName = ApiClient.convertToType(data['targetCaseName'], 'String');
      if (data.hasOwnProperty('targetCaseSlot'))
        obj.targetCaseSlot = ApiClient.convertToType(data['targetCaseSlot'], 'String');
    }
    return obj;
  }
}

/**
 * The relation source case name (immutable)
 * @member {String} sourceCaseName
 */
CaseRelationReference.prototype.sourceCaseName = undefined;

/**
 * The relation source case slot
 * @member {String} sourceCaseSlot
 */
CaseRelationReference.prototype.sourceCaseSlot = undefined;

/**
 * The relation target case name (immutable)
 * @member {String} targetCaseName
 */
CaseRelationReference.prototype.targetCaseName = undefined;

/**
 * The relation target case slot
 * @member {String} targetCaseSlot
 */
CaseRelationReference.prototype.targetCaseSlot = undefined;

