/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CaseFieldBasicFields} from './CaseFieldBasicFields';

/**
 * The CaseFieldBasic model module.
 * @module model/CaseFieldBasic
 * @version 1.0.11
 */
export class CaseFieldBasic {
  /**
   * Constructs a new <code>CaseFieldBasic</code>.
   * @alias module:model/CaseFieldBasic
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CaseFieldBasic</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseFieldBasic} obj Optional instance to populate.
   * @return {module:model/CaseFieldBasic} The populated <code>CaseFieldBasic</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseFieldBasic();
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [CaseFieldBasicFields]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CaseFieldBasicFields>} fields
 */
CaseFieldBasic.prototype.fields = undefined;

