/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The CaseSlot model module.
 * @module model/CaseSlot
 * @version 1
 */
export class CaseSlot {
  /**
   * Constructs a new <code>CaseSlot</code>.
   * Case slot
   * @alias module:model/CaseSlot
   * @class
   * @param name {String} The case slot name
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>CaseSlot</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseSlot} obj Optional instance to populate.
   * @return {module:model/CaseSlot} The populated <code>CaseSlot</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseSlot();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nameLocalizations'))
        obj.nameLocalizations = ApiClient.convertToType(data['nameLocalizations'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * The case slot name
 * @member {String} name
 */
CaseSlot.prototype.name = undefined;

/**
 * The localized case slot names
 * @member {Object.<String, String>} nameLocalizations
 */
CaseSlot.prototype.nameLocalizations = undefined;

