/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CaseField} from './CaseField';

/**
 * The CaseValuesResponseBody model module.
 * @module model/CaseValuesResponseBody
 * @version 1.0.11
 */
export class CaseValuesResponseBody {
  /**
   * Constructs a new <code>CaseValuesResponseBody</code>.
   * @alias module:model/CaseValuesResponseBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CaseValuesResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseValuesResponseBody} obj Optional instance to populate.
   * @return {module:model/CaseValuesResponseBody} The populated <code>CaseValuesResponseBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseValuesResponseBody();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [CaseField]);
    }
    return obj;
  }
}

/**
 * The case name (immutable)
 * @member {String} name
 */
CaseValuesResponseBody.prototype.name = undefined;

/**
 * @member {Array.<module:model/CaseField>} fields
 */
CaseValuesResponseBody.prototype.fields = undefined;

