/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The CaseFieldReference model module.
 * @module model/CaseFieldReference
 * @version 1
 */
export class CaseFieldReference {
  /**
   * Constructs a new <code>CaseFieldReference</code>.
   * Case field reference
   * @alias module:model/CaseFieldReference
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CaseFieldReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseFieldReference} obj Optional instance to populate.
   * @return {module:model/CaseFieldReference} The populated <code>CaseFieldReference</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseFieldReference();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
    }
    return obj;
  }
}

/**
 * The case field name
 * @member {String} name
 */
CaseFieldReference.prototype.name = undefined;

/**
 * The case field order
 * @member {Number} order
 */
CaseFieldReference.prototype.order = undefined;

