/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CaseFieldValue} from './CaseFieldValue';

/**
 * The CaseFieldBasicFields model module.
 * @module model/CaseFieldBasicFields
 * @version 1.0.11
 */
export class CaseFieldBasicFields {
  /**
   * Constructs a new <code>CaseFieldBasicFields</code>.
   * @alias module:model/CaseFieldBasicFields
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CaseFieldBasicFields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseFieldBasicFields} obj Optional instance to populate.
   * @return {module:model/CaseFieldBasicFields} The populated <code>CaseFieldBasicFields</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseFieldBasicFields();
      if (data.hasOwnProperty('caseName'))
        obj.caseName = ApiClient.convertToType(data['caseName'], 'String');
      if (data.hasOwnProperty('fieldName'))
        obj.fieldName = ApiClient.convertToType(data['fieldName'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = CaseFieldValue.constructFromObject(data['value']);
    }
    return obj;
  }
}

/**
 * The name of the case which the field is a member of (immutable)
 * @member {String} caseName
 */
CaseFieldBasicFields.prototype.caseName = undefined;

/**
 * The case field name (immutable)
 * @member {String} fieldName
 */
CaseFieldBasicFields.prototype.fieldName = undefined;

/**
 * @member {module:model/CaseFieldValue} value
 */
CaseFieldBasicFields.prototype.value = undefined;

