/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {CaseValueSetup} from './CaseValueSetup';
import {ObjectStatus} from './ObjectStatus';

/**
 * The CaseSetup model module.
 * @module model/CaseSetup
 * @version 1
 */
export class CaseSetup {
  /**
   * Constructs a new <code>CaseSetup</code>.
   * Case setup
   * @alias module:model/CaseSetup
   * @class
   * @param caseName {String} The case name
   */
  constructor(caseName) {
    this.caseName = caseName;
  }

  /**
   * Constructs a <code>CaseSetup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseSetup} obj Optional instance to populate.
   * @return {module:model/CaseSetup} The populated <code>CaseSetup</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CaseSetup();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('caseName'))
        obj.caseName = ApiClient.convertToType(data['caseName'], 'String');
      if (data.hasOwnProperty('caseSlot'))
        obj.caseSlot = ApiClient.convertToType(data['caseSlot'], 'String');
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], [CaseValueSetup]);
      if (data.hasOwnProperty('relatedCases'))
        obj.relatedCases = ApiClient.convertToType(data['relatedCases'], [CaseSetup]);
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
CaseSetup.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
CaseSetup.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
CaseSetup.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
CaseSetup.prototype.updated = undefined;

/**
 * The case name
 * @member {String} caseName
 */
CaseSetup.prototype.caseName = undefined;

/**
 * The case slot
 * @member {String} caseSlot
 */
CaseSetup.prototype.caseSlot = undefined;

/**
 * The case value setups
 * @member {Array.<module:model/CaseValueSetup>} values
 */
CaseSetup.prototype.values = undefined;

/**
 * The related cases
 * @member {Array.<module:model/CaseSetup>} relatedCases
 */
CaseSetup.prototype.relatedCases = undefined;

