/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */


/**
 * Enum class CaseIssueType.
 * @enum {String}
 * @readonly
 */
const CaseIssueType = {
  /**
   * value: "Unknown"
   * @const
   */
  unknown: "Unknown",

  /**
   * value: "CaseInvalid"
   * @const
   */
  caseInvalid: "CaseInvalid",

  /**
   * value: "CaseUnknown"
   * @const
   */
  caseUnknown: "CaseUnknown",

  /**
   * value: "CaseRelationInvalid"
   * @const
   */
  caseRelationInvalid: "CaseRelationInvalid",

  /**
   * value: "CaseFieldDuplicated"
   * @const
   */
  caseFieldDuplicated: "CaseFieldDuplicated",

  /**
   * value: "CaseValueIncomplete"
   * @const
   */
  caseValueIncomplete: "CaseValueIncomplete",

  /**
   * value: "CaseValueStartInvalid"
   * @const
   */
  caseValueStartInvalid: "CaseValueStartInvalid",

  /**
   * value: "CaseValueEndInvalid"
   * @const
   */
  caseValueEndInvalid: "CaseValueEndInvalid",

  /**
   * value: "CaseValueEndMissing"
   * @const
   */
  caseValueEndMissing: "CaseValueEndMissing",

  /**
   * Returns a <code>CaseIssueType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/CaseIssueType} The enum <code>CaseIssueType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {CaseIssueType};