/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';
import {ValueType} from './ValueType';

/**
 * The CollectorCustomResult model module.
 * @module model/CollectorCustomResult
 * @version 1
 */
export class CollectorCustomResult {
  /**
   * Constructs a new <code>CollectorCustomResult</code>.
   * The collector custom result API object
   * @alias module:model/CollectorCustomResult
   * @class
   * @param collectorName {String} The collector name (immutable)
   * @param source {String} The value source (immutable)
   * @param valueType {module:model/ValueType} 
   * @param value {Number} The collector result value (immutable)
   * @param start {Date} The period starting date for the value
   * @param end {Date} The period ending date for the value
   */
  constructor(collectorName, source, valueType, value, start, end) {
    this.collectorName = collectorName;
    this.source = source;
    this.valueType = valueType;
    this.value = value;
    this.start = start;
    this.end = end;
  }

  /**
   * Constructs a <code>CollectorCustomResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CollectorCustomResult} obj Optional instance to populate.
   * @return {module:model/CollectorCustomResult} The populated <code>CollectorCustomResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CollectorCustomResult();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('collectorResultId'))
        obj.collectorResultId = ApiClient.convertToType(data['collectorResultId'], 'Number');
      if (data.hasOwnProperty('collectorName'))
        obj.collectorName = ApiClient.convertToType(data['collectorName'], 'String');
      if (data.hasOwnProperty('collectorNameLocalizations'))
        obj.collectorNameLocalizations = ApiClient.convertToType(data['collectorNameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('valueType'))
        obj.valueType = ValueType.constructFromObject(data['valueType']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
CollectorCustomResult.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
CollectorCustomResult.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
CollectorCustomResult.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
CollectorCustomResult.prototype.updated = undefined;

/**
 * The wage type result id (immutable)
 * @member {Number} collectorResultId
 */
CollectorCustomResult.prototype.collectorResultId = undefined;

/**
 * The collector name (immutable)
 * @member {String} collectorName
 */
CollectorCustomResult.prototype.collectorName = undefined;

/**
 * The localized collector names (immutable)
 * @member {Object.<String, String>} collectorNameLocalizations
 */
CollectorCustomResult.prototype.collectorNameLocalizations = undefined;

/**
 * The value source (immutable)
 * @member {String} source
 */
CollectorCustomResult.prototype.source = undefined;

/**
 * @member {module:model/ValueType} valueType
 */
CollectorCustomResult.prototype.valueType = undefined;

/**
 * The collector result value (immutable)
 * @member {Number} value
 */
CollectorCustomResult.prototype.value = undefined;

/**
 * The period starting date for the value
 * @member {Date} start
 */
CollectorCustomResult.prototype.start = undefined;

/**
 * The period ending date for the value
 * @member {Date} end
 */
CollectorCustomResult.prototype.end = undefined;

/**
 * The result tags
 * @member {Array.<String>} tags
 */
CollectorCustomResult.prototype.tags = undefined;

/**
 * The result attributes (immutable)
 * @member {Object.<String, Object>} attributes
 */
CollectorCustomResult.prototype.attributes = undefined;

