/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CollectorResult} from './CollectorResult';
import {PayrunResult} from './PayrunResult';
import {WageTypeResultSet} from './WageTypeResultSet';

/**
 * The ConsolidatedPayrollResult model module.
 * @module model/ConsolidatedPayrollResult
 * @version 1
 */
export class ConsolidatedPayrollResult {
  /**
   * Constructs a new <code>ConsolidatedPayrollResult</code>.
   * A consolidated payroll result
   * @alias module:model/ConsolidatedPayrollResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ConsolidatedPayrollResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConsolidatedPayrollResult} obj Optional instance to populate.
   * @return {module:model/ConsolidatedPayrollResult} The populated <code>ConsolidatedPayrollResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ConsolidatedPayrollResult();
      if (data.hasOwnProperty('wageTypeResults'))
        obj.wageTypeResults = ApiClient.convertToType(data['wageTypeResults'], [WageTypeResultSet]);
      if (data.hasOwnProperty('collectorResults'))
        obj.collectorResults = ApiClient.convertToType(data['collectorResults'], [CollectorResult]);
      if (data.hasOwnProperty('payrunResults'))
        obj.payrunResults = ApiClient.convertToType(data['payrunResults'], [PayrunResult]);
    }
    return obj;
  }
}

/**
 * The wage type results
 * @member {Array.<module:model/WageTypeResultSet>} wageTypeResults
 */
ConsolidatedPayrollResult.prototype.wageTypeResults = undefined;

/**
 * The collector results
 * @member {Array.<module:model/CollectorResult>} collectorResults
 */
ConsolidatedPayrollResult.prototype.collectorResults = undefined;

/**
 * The payrun results
 * @member {Array.<module:model/PayrunResult>} payrunResults
 */
ConsolidatedPayrollResult.prototype.payrunResults = undefined;

