/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DataRow model module.
 * @module model/DataRow
 * @version 1
 */
export class DataRow {
  /**
   * Constructs a new <code>DataRow</code>.
   * Represents a row of data in a DataTable
   * @alias module:model/DataRow
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DataRow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataRow} obj Optional instance to populate.
   * @return {module:model/DataRow} The populated <code>DataRow</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DataRow();
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], ['String']);
    }
    return obj;
  }
}

/**
 * Gets or sets the row values (JSON, type matching to the column)
 * @member {Array.<String>} values
 */
DataRow.prototype.values = undefined;

