/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DatePeriod model module.
 * @module model/DatePeriod
 * @version 1
 */
export class DatePeriod {
  /**
   * Constructs a new <code>DatePeriod</code>.
   * A date period between the start and end date
   * @alias module:model/DatePeriod
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DatePeriod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatePeriod} obj Optional instance to populate.
   * @return {module:model/DatePeriod} The populated <code>DatePeriod</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DatePeriod();
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
    }
    return obj;
  }
}

/**
 * The period start
 * @member {Date} start
 */
DatePeriod.prototype.start = undefined;

/**
 * The period end
 * @member {Date} end
 */
DatePeriod.prototype.end = undefined;

