/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';

/**
 * The Division model module.
 * @module model/Division
 * @version 1
 */
export class Division {
  /**
   * Constructs a new <code>Division</code>.
   * The division API object
   * @alias module:model/Division
   * @class
   * @param name {String} The division name
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Division</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Division} obj Optional instance to populate.
   * @return {module:model/Division} The populated <code>Division</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Division();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nameLocalizations'))
        obj.nameLocalizations = ApiClient.convertToType(data['nameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('culture'))
        obj.culture = ApiClient.convertToType(data['culture'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
Division.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
Division.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
Division.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
Division.prototype.updated = undefined;

/**
 * The division name
 * @member {String} name
 */
Division.prototype.name = undefined;

/**
 * The localized division names
 * @member {Object.<String, String>} nameLocalizations
 */
Division.prototype.nameLocalizations = undefined;

/**
 * The culture including the calendar, fallback of employee culture
 * @member {String} culture
 */
Division.prototype.culture = undefined;

/**
 * Custom attributes
 * @member {Object.<String, Object>} attributes
 */
Division.prototype.attributes = undefined;

