/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DivisionScope.
 * @enum {String}
 * @readonly
 */
const DivisionScope = {
  /**
   * value: "All"
   * @const
   */
  all: "All",

  /**
   * value: "Local"
   * @const
   */
  local: "Local",

  /**
   * value: "Global"
   * @const
   */
  global: "Global",

  /**
   * value: "GlobalAndLocal"
   * @const
   */
  globalAndLocal: "GlobalAndLocal",

  /**
   * Returns a <code>DivisionScope</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DivisionScope} The enum <code>DivisionScope</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DivisionScope};