/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentStatus} from './DocumentStatus';

/**
 * The Document model module.
 * @module model/Document
 * @version 1.0.11
 */
export class Document {
  /**
   * Constructs a new <code>Document</code>.
   * @alias module:model/Document
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Document</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Document} obj Optional instance to populate.
   * @return {module:model/Document} The populated <code>Document</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Document();
      if (data.hasOwnProperty('documentId'))
        obj.documentId = ApiClient.convertToType(data['documentId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = DocumentStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} documentId
 */
Document.prototype.documentId = undefined;

/**
 * @member {String} name
 */
Document.prototype.name = undefined;

/**
 * @member {module:model/DocumentStatus} status
 */
Document.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {String} created
 */
Document.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {String} updated
 */
Document.prototype.updated = undefined;

/**
 * The document content
 * @member {String} content
 */
Document.prototype.content = undefined;

