/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Document} from './Document';

/**
 * The DocumentsResponseBody model module.
 * @module model/DocumentsResponseBody
 * @version 1.0.11
 */
export class DocumentsResponseBody {
  /**
   * Constructs a new <code>DocumentsResponseBody</code>.
   * @alias module:model/DocumentsResponseBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentsResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentsResponseBody} obj Optional instance to populate.
   * @return {module:model/DocumentsResponseBody} The populated <code>DocumentsResponseBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentsResponseBody();
      if (data.hasOwnProperty('documents'))
        obj.documents = ApiClient.convertToType(data['documents'], [Document]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Document>} documents
 */
DocumentsResponseBody.prototype.documents = undefined;

