/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */

/**
 * Enum class EventAttributes.
 * @enum {Number}
 * @readonly
 */
const EventAttributes = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 512
   * @const
   */
  _512: 512,

  /**
   * value: 1024
   * @const
   */
  _1024: 1024,

  /**
   * Returns a <code>EventAttributes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/EventAttributes} The enum <code>EventAttributes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {EventAttributes};