/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {MethodBase} from './MethodBase';

/**
 * The Exception model module.
 * @module model/Exception
 * @version 1
 */
export class Exception {
  /**
   * Constructs a new <code>Exception</code>.
   * @alias module:model/Exception
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Exception</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exception} obj Optional instance to populate.
   * @return {module:model/Exception} The populated <code>Exception</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Exception();
      if (data.hasOwnProperty('targetSite'))
        obj.targetSite = MethodBase.constructFromObject(data['targetSite']);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], {'String': Object});
      if (data.hasOwnProperty('innerException'))
        obj.innerException = Exception.constructFromObject(data['innerException']);
      if (data.hasOwnProperty('helpLink'))
        obj.helpLink = ApiClient.convertToType(data['helpLink'], 'String');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('hResult'))
        obj.hResult = ApiClient.convertToType(data['hResult'], 'Number');
      if (data.hasOwnProperty('stackTrace'))
        obj.stackTrace = ApiClient.convertToType(data['stackTrace'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/MethodBase} targetSite
 */
Exception.prototype.targetSite = undefined;

/**
 * @member {String} message
 */
Exception.prototype.message = undefined;

/**
 * @member {Object.<String, Object>} data
 */
Exception.prototype.data = undefined;

/**
 * @member {module:model/Exception} innerException
 */
Exception.prototype.innerException = undefined;

/**
 * @member {String} helpLink
 */
Exception.prototype.helpLink = undefined;

/**
 * @member {String} source
 */
Exception.prototype.source = undefined;

/**
 * @member {Number} hResult
 */
Exception.prototype.hResult = undefined;

/**
 * @member {String} stackTrace
 */
Exception.prototype.stackTrace = undefined;

