/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */

/**
 * Enum class Language.
 * @enum {String}
 * @readonly
 */
const Language = {
  /**
   * value: "English"
   * @const
   */
  english: "English",

  /**
   * value: "Afrikaans"
   * @const
   */
  afrikaans: "Afrikaans",

  /**
   * value: "Arabic"
   * @const
   */
  arabic: "Arabic",

  /**
   * value: "Azerbaijani"
   * @const
   */
  azerbaijani: "Azerbaijani",

  /**
   * value: "Belarusian"
   * @const
   */
  belarusian: "Belarusian",

  /**
   * value: "Bulgarian"
   * @const
   */
  bulgarian: "Bulgarian",

  /**
   * value: "Bosnian"
   * @const
   */
  bosnian: "Bosnian",

  /**
   * value: "Czech"
   * @const
   */
  czech: "Czech",

  /**
   * value: "Danish"
   * @const
   */
  danish: "Danish",

  /**
   * value: "German"
   * @const
   */
  german: "German",

  /**
   * value: "Greek"
   * @const
   */
  greek: "Greek",

  /**
   * value: "Spanish"
   * @const
   */
  spanish: "Spanish",

  /**
   * value: "Estonian"
   * @const
   */
  estonian: "Estonian",

  /**
   * value: "Persian"
   * @const
   */
  persian: "Persian",

  /**
   * value: "Finnish"
   * @const
   */
  finnish: "Finnish",

  /**
   * value: "French"
   * @const
   */
  french: "French",

  /**
   * value: "Irish"
   * @const
   */
  irish: "Irish",

  /**
   * value: "Hebrew"
   * @const
   */
  hebrew: "Hebrew",

  /**
   * value: "Hindi"
   * @const
   */
  hindi: "Hindi",

  /**
   * value: "Croatian"
   * @const
   */
  croatian: "Croatian",

  /**
   * value: "Hungarian"
   * @const
   */
  hungarian: "Hungarian",

  /**
   * value: "Armenian"
   * @const
   */
  armenian: "Armenian",

  /**
   * value: "Icelandic"
   * @const
   */
  icelandic: "Icelandic",

  /**
   * value: "Italian"
   * @const
   */
  italian: "Italian",

  /**
   * value: "Japanese"
   * @const
   */
  japanese: "Japanese",

  /**
   * value: "Georgian"
   * @const
   */
  georgian: "Georgian",

  /**
   * value: "Korean"
   * @const
   */
  korean: "Korean",

  /**
   * value: "Luxembourgish"
   * @const
   */
  luxembourgish: "Luxembourgish",

  /**
   * value: "Lithuanian"
   * @const
   */
  lithuanian: "Lithuanian",

  /**
   * value: "Latvian"
   * @const
   */
  latvian: "Latvian",

  /**
   * value: "Macedonian"
   * @const
   */
  macedonian: "Macedonian",

  /**
   * value: "Dutch"
   * @const
   */
  dutch: "Dutch",

  /**
   * value: "Norwegian"
   * @const
   */
  norwegian: "Norwegian",

  /**
   * value: "Polish"
   * @const
   */
  polish: "Polish",

  /**
   * value: "Portuguese"
   * @const
   */
  portuguese: "Portuguese",

  /**
   * value: "Romanian"
   * @const
   */
  romanian: "Romanian",

  /**
   * value: "Russian"
   * @const
   */
  russian: "Russian",

  /**
   * value: "Slovak"
   * @const
   */
  slovak: "Slovak",

  /**
   * value: "Slovenian"
   * @const
   */
  slovenian: "Slovenian",

  /**
   * value: "Albanian"
   * @const
   */
  albanian: "Albanian",

  /**
   * value: "Serbian"
   * @const
   */
  serbian: "Serbian",

  /**
   * value: "Swedish"
   * @const
   */
  swedish: "Swedish",

  /**
   * value: "Thai"
   * @const
   */
  thai: "Thai",

  /**
   * value: "Turkish"
   * @const
   */
  turkish: "Turkish",

  /**
   * value: "Ukrainian"
   * @const
   */
  ukrainian: "Ukrainian",

  /**
   * value: "Uzbek"
   * @const
   */
  uzbek: "Uzbek",

  /**
   * value: "Vietnamese"
   * @const
   */
  vietnamese: "Vietnamese",

  /**
   * value: "Chinese"
   * @const
   */
  chinese: "Chinese",

  /**
   * Returns a <code>Language</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Language} The enum <code>Language</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Language};