/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class LogLevel.
 * @enum {String}
 * @readonly
 */
const LogLevel = {
  /**
   * value: "Verbose"
   * @const
   */
  verbose: "Verbose",

  /**
   * value: "Debug"
   * @const
   */
  debug: "Debug",

  /**
   * value: "Information"
   * @const
   */
  information: "Information",

  /**
   * value: "Warning"
   * @const
   */
  warning: "Warning",

  /**
   * value: "Error"
   * @const
   */
  error: "Error",

  /**
   * value: "Fatal"
   * @const
   */
  fatal: "Fatal",

  /**
   * Returns a <code>LogLevel</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/LogLevel} The enum <code>LogLevel</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {LogLevel};