/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The LookupSettings model module.
 * @module model/LookupSettings
 * @version 1
 */
export class LookupSettings {
  /**
   * Constructs a new <code>LookupSettings</code>.
   * The lookup settings
   * @alias module:model/LookupSettings
   * @class
   * @param lookupName {String} The lookup name
   */
  constructor(lookupName) {
    this.lookupName = lookupName;
  }

  /**
   * Constructs a <code>LookupSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LookupSettings} obj Optional instance to populate.
   * @return {module:model/LookupSettings} The populated <code>LookupSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LookupSettings();
      if (data.hasOwnProperty('lookupName'))
        obj.lookupName = ApiClient.convertToType(data['lookupName'], 'String');
      if (data.hasOwnProperty('valueFieldName'))
        obj.valueFieldName = ApiClient.convertToType(data['valueFieldName'], 'String');
      if (data.hasOwnProperty('textFieldName'))
        obj.textFieldName = ApiClient.convertToType(data['textFieldName'], 'String');
    }
    return obj;
  }
}

/**
 * The lookup name
 * @member {String} lookupName
 */
LookupSettings.prototype.lookupName = undefined;

/**
 * The lookup value field name
 * @member {String} valueFieldName
 */
LookupSettings.prototype.valueFieldName = undefined;

/**
 * The lookup text/display field name
 * @member {String} textFieldName
 */
LookupSettings.prototype.textFieldName = undefined;

