/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LookupValue} from './LookupValue';
import {ObjectStatus} from './ObjectStatus';
import {OverrideType} from './OverrideType';

/**
 * The LookupSet model module.
 * @module model/LookupSet
 * @version 1
 */
export class LookupSet {
  /**
   * Constructs a new <code>LookupSet</code>.
   * Lookup including the lookup value
   * @alias module:model/LookupSet
   * @class
   * @param name {String} The unique lookup name (immutable)
   * @param values {Array.<module:model/LookupValue>} The lookup values
   */
  constructor(name, values) {
    this.name = name;
    this.values = values;
  }

  /**
   * Constructs a <code>LookupSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LookupSet} obj Optional instance to populate.
   * @return {module:model/LookupSet} The populated <code>LookupSet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LookupSet();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nameLocalizations'))
        obj.nameLocalizations = ApiClient.convertToType(data['nameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('descriptionLocalizations'))
        obj.descriptionLocalizations = ApiClient.convertToType(data['descriptionLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('overrideType'))
        obj.overrideType = OverrideType.constructFromObject(data['overrideType']);
      if (data.hasOwnProperty('rangeSize'))
        obj.rangeSize = ApiClient.convertToType(data['rangeSize'], 'Number');
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], [LookupValue]);
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
LookupSet.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
LookupSet.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
LookupSet.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
LookupSet.prototype.updated = undefined;

/**
 * The unique lookup name (immutable)
 * @member {String} name
 */
LookupSet.prototype.name = undefined;

/**
 * The localized lookup names
 * @member {Object.<String, String>} nameLocalizations
 */
LookupSet.prototype.nameLocalizations = undefined;

/**
 * The lookup description
 * @member {String} description
 */
LookupSet.prototype.description = undefined;

/**
 * The localized lookup descriptions
 * @member {Object.<String, String>} descriptionLocalizations
 */
LookupSet.prototype.descriptionLocalizations = undefined;

/**
 * @member {module:model/OverrideType} overrideType
 */
LookupSet.prototype.overrideType = undefined;

/**
 * The lookup range size
 * @member {Number} rangeSize
 */
LookupSet.prototype.rangeSize = undefined;

/**
 * The lookup values
 * @member {Array.<module:model/LookupValue>} values
 */
LookupSet.prototype.values = undefined;

