/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The LookupValueData model module.
 * @module model/LookupValueData
 * @version 1
 */
export class LookupValueData {
  /**
   * Constructs a new <code>LookupValueData</code>.
   * Lookup value date in a specific language
   * @alias module:model/LookupValueData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LookupValueData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LookupValueData} obj Optional instance to populate.
   * @return {module:model/LookupValueData} The populated <code>LookupValueData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LookupValueData();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('rangeValue'))
        obj.rangeValue = ApiClient.convertToType(data['rangeValue'], 'Number');
    }
    return obj;
  }
}

/**
 * The lookup key
 * @member {String} key
 */
LookupValueData.prototype.key = undefined;

/**
 * The lookup value as JSON
 * @member {String} value
 */
LookupValueData.prototype.value = undefined;

/**
 * The lookup range value
 * @member {Number} rangeValue
 */
LookupValueData.prototype.rangeValue = undefined;

