/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {Language} from './Language';
import {LookupValueData} from './LookupValueData';

/**
 * The LookupData model module.
 * @module model/LookupData
 * @version 1
 */
export class LookupData {
  /**
   * Constructs a new <code>LookupData</code>.
   * Localized lookup for UI cases like list/grid selections
   * @alias module:model/LookupData
   * @class
   * @param name {String} The lookup name
   * @param values {Array.<module:model/LookupValueData>} The lookup values
   */
  constructor(name, values) {
    this.name = name;
    this.values = values;
  }

  /**
   * Constructs a <code>LookupData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LookupData} obj Optional instance to populate.
   * @return {module:model/LookupData} The populated <code>LookupData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LookupData();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = Language.constructFromObject(data['language']);
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], [LookupValueData]);
      if (data.hasOwnProperty('rangeSize'))
        obj.rangeSize = ApiClient.convertToType(data['rangeSize'], 'Number');
    }
    return obj;
  }
}

/**
 * The lookup name
 * @member {String} name
 */
LookupData.prototype.name = undefined;

/**
 * @member {module:model/Language} language
 */
LookupData.prototype.language = undefined;

/**
 * The lookup values
 * @member {Array.<module:model/LookupValueData>} values
 */
LookupData.prototype.values = undefined;

/**
 * The lookup range size
 * @member {Number} rangeSize
 */
LookupData.prototype.rangeSize = undefined;

