/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {Exception} from './Exception';

/**
 * The ModelError model module.
 * @module model/ModelError
 * @version 1
 */
export class ModelError {
  /**
   * Constructs a new <code>ModelError</code>.
   * @alias module:model/ModelError
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelError} obj Optional instance to populate.
   * @return {module:model/ModelError} The populated <code>ModelError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelError();
      if (data.hasOwnProperty('exception'))
        obj.exception = Exception.constructFromObject(data['exception']);
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Exception} exception
 */
ModelError.prototype.exception = undefined;

/**
 * @member {String} errorMessage
 */
ModelError.prototype.errorMessage = undefined;

