/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * The ModuleHandle model module.
 * @module model/ModuleHandle
 * @version 1
 */
export class ModuleHandle {
  /**
   * Constructs a new <code>ModuleHandle</code>.
   * @alias module:model/ModuleHandle
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModuleHandle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModuleHandle} obj Optional instance to populate.
   * @return {module:model/ModuleHandle} The populated <code>ModuleHandle</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModuleHandle();
      if (data.hasOwnProperty('mdStreamVersion'))
        obj.mdStreamVersion = ApiClient.convertToType(data['mdStreamVersion'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} mdStreamVersion
 */
ModuleHandle.prototype.mdStreamVersion = undefined;

