/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */

/**
 * Enum class ParameterAttributes.
 * @enum {Number}
 * @readonly
 */
const ParameterAttributes = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * value: 16
   * @const
   */
  _16: 16,

  /**
   * value: 4096
   * @const
   */
  _4096: 4096,

  /**
   * value: 8192
   * @const
   */
  _8192: 8192,

  /**
   * value: 16384
   * @const
   */
  _16384: 16384,

  /**
   * value: 32768
   * @const
   */
  _32768: 32768,

  /**
   * value: 61440
   * @const
   */
  _61440: 61440,

  /**
   * Returns a <code>ParameterAttributes</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ParameterAttributes} The enum <code>ParameterAttributes</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ParameterAttributes};