/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';

/**
 * The PayrollLayer model module.
 * @module model/PayrollLayer
 * @version 1
 */
export class PayrollLayer {
  /**
   * Constructs a new <code>PayrollLayer</code>.
   * The payroll layer API object.  Payroll layer evaluated order in payrolls:  1. From th highest level to the lowest level  2. Within a level: from th highest priority to the lowest priority
   * @alias module:model/PayrollLayer
   * @class
   * @param level {Number} The layer level, used as primary sorting key (descending)
   * @param priority {Number} The layer priority, used as secondary sorting key (descending)
   * @param regulationName {String} The regulation name
   */
  constructor(level, priority, regulationName) {
    this.level = level;
    this.priority = priority;
    this.regulationName = regulationName;
  }

  /**
   * Constructs a <code>PayrollLayer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayrollLayer} obj Optional instance to populate.
   * @return {module:model/PayrollLayer} The populated <code>PayrollLayer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PayrollLayer();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
      if (data.hasOwnProperty('priority'))
        obj.priority = ApiClient.convertToType(data['priority'], 'Number');
      if (data.hasOwnProperty('regulationName'))
        obj.regulationName = ApiClient.convertToType(data['regulationName'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
PayrollLayer.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
PayrollLayer.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
PayrollLayer.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
PayrollLayer.prototype.updated = undefined;

/**
 * The layer level, used as primary sorting key (descending)
 * @member {Number} level
 */
PayrollLayer.prototype.level = undefined;

/**
 * The layer priority, used as secondary sorting key (descending)
 * @member {Number} priority
 */
PayrollLayer.prototype.priority = undefined;

/**
 * The regulation name
 * @member {String} regulationName
 */
PayrollLayer.prototype.regulationName = undefined;

/**
 * Custom attributes
 * @member {Object.<String, Object>} attributes
 */
PayrollLayer.prototype.attributes = undefined;

