/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class PayrunJobStatus.
 * @enum {String}
 * @readonly
 */
const PayrunJobStatus = {
  /**
   * value: "Draft"
   * @const
   */
  draft: "Draft",

  /**
   * value: "Release"
   * @const
   */
  release: "Release",

  /**
   * value: "Process"
   * @const
   */
  process: "Process",

  /**
   * value: "Working"
   * @const
   */
  working: "Working",

  /**
   * value: "Complete"
   * @const
   */
  complete: "Complete",

  /**
   * value: "Legal"
   * @const
   */
  legal: "Legal",

  /**
   * value: "Forecast"
   * @const
   */
  forecast: "Forecast",

  /**
   * value: "Abort"
   * @const
   */
  abort: "Abort",

  /**
   * value: "Cancel"
   * @const
   */
  cancel: "Cancel",

  /**
   * value: "Final"
   * @const
   */
  _final: "Final",

  /**
   * Returns a <code>PayrunJobStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/PayrunJobStatus} The enum <code>PayrunJobStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {PayrunJobStatus};