/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';
import {ValueType} from './ValueType';

/**
 * The PayrunResult model module.
 * @module model/PayrunResult
 * @version 1
 */
export class PayrunResult {
  /**
   * Constructs a new <code>PayrunResult</code>.
   * The payrun result API object
   * @alias module:model/PayrunResult
   * @class
   * @param source {String} The result source (immutable)
   * @param name {String} The result name (immutable)
   * @param valueType {module:model/ValueType} 
   * @param value {String} The result value (immutable)
   * @param start {Date} The period starting date for the value
   * @param end {Date} The period ending date for the value
   */
  constructor(source, name, valueType, value, start, end) {
    this.source = source;
    this.name = name;
    this.valueType = valueType;
    this.value = value;
    this.start = start;
    this.end = end;
  }

  /**
   * Constructs a <code>PayrunResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayrunResult} obj Optional instance to populate.
   * @return {module:model/PayrunResult} The populated <code>PayrunResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PayrunResult();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('payrollResultId'))
        obj.payrollResultId = ApiClient.convertToType(data['payrollResultId'], 'Number');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nameLocalizations'))
        obj.nameLocalizations = ApiClient.convertToType(data['nameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('slot'))
        obj.slot = ApiClient.convertToType(data['slot'], 'String');
      if (data.hasOwnProperty('valueType'))
        obj.valueType = ValueType.constructFromObject(data['valueType']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('numericValue'))
        obj.numericValue = ApiClient.convertToType(data['numericValue'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
PayrunResult.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
PayrunResult.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
PayrunResult.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
PayrunResult.prototype.updated = undefined;

/**
 * The payroll result id (immutable)
 * @member {Number} payrollResultId
 */
PayrunResult.prototype.payrollResultId = undefined;

/**
 * The result source (immutable)
 * @member {String} source
 */
PayrunResult.prototype.source = undefined;

/**
 * The result name (immutable)
 * @member {String} name
 */
PayrunResult.prototype.name = undefined;

/**
 * The localized result names
 * @member {Object.<String, String>} nameLocalizations
 */
PayrunResult.prototype.nameLocalizations = undefined;

/**
 * The result slot (immutable)
 * @member {String} slot
 */
PayrunResult.prototype.slot = undefined;

/**
 * @member {module:model/ValueType} valueType
 */
PayrunResult.prototype.valueType = undefined;

/**
 * The result value (immutable)
 * @member {String} value
 */
PayrunResult.prototype.value = undefined;

/**
 * The numeric result value (immutable)
 * @member {Number} numericValue
 */
PayrunResult.prototype.numericValue = undefined;

/**
 * The period starting date for the value
 * @member {Date} start
 */
PayrunResult.prototype.start = undefined;

/**
 * The period ending date for the value
 * @member {Date} end
 */
PayrunResult.prototype.end = undefined;

/**
 * The result tags
 * @member {Array.<String>} tags
 */
PayrunResult.prototype.tags = undefined;

/**
 * The result attributes (immutable)
 * @member {Object.<String, Object>} attributes
 */
PayrunResult.prototype.attributes = undefined;

