/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class PayrunJobExecutionMode.
 * @enum {String}
 * @readonly
 */
const PayrunJobExecutionMode = {
  /**
   * value: "Synchronous"
   * @const
   */
  synchronous: "Synchronous",

  /**
   * value: "Asynchronous"
   * @const
   */
  asynchronous: "Asynchronous",

  /**
   * Returns a <code>PayrunJobExecutionMode</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/PayrunJobExecutionMode} The enum <code>PayrunJobExecutionMode</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {PayrunJobExecutionMode};