/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';

/**
 * The ReportLog model module.
 * @module model/ReportLog
 * @version 1
 */
export class ReportLog {
  /**
   * Constructs a new <code>ReportLog</code>.
   * A payroll report log
   * @alias module:model/ReportLog
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReportLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportLog} obj Optional instance to populate.
   * @return {module:model/ReportLog} The populated <code>ReportLog</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReportLog();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('reportName'))
        obj.reportName = ApiClient.convertToType(data['reportName'], 'String');
      if (data.hasOwnProperty('reportDate'))
        obj.reportDate = ApiClient.convertToType(data['reportDate'], 'Date');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
ReportLog.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
ReportLog.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
ReportLog.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
ReportLog.prototype.updated = undefined;

/**
 * The report name (immutable)
 * @member {String} reportName
 */
ReportLog.prototype.reportName = undefined;

/**
 * The report date (immutable)
 * @member {Date} reportDate
 */
ReportLog.prototype.reportDate = undefined;

/**
 * The report log key (immutable)
 * @member {String} key
 */
ReportLog.prototype.key = undefined;

/**
 * The report user (immutable)
 * @member {String} user
 */
ReportLog.prototype.user = undefined;

/**
 * The report message (immutable)
 * @member {String} message
 */
ReportLog.prototype.message = undefined;

