/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DataRelation} from './DataRelation';
import {DataSet} from './DataSet';
import {Language} from './Language';

/**
 * The ReportResponse model module.
 * @module model/ReportResponse
 * @version 1
 */
export class ReportResponse {
  /**
   * Constructs a new <code>ReportResponse</code>.
   * The report response API object
   * @alias module:model/ReportResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReportResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportResponse} obj Optional instance to populate.
   * @return {module:model/ReportResponse} The populated <code>ReportResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReportResponse();
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], {'String': 'String'});
      if (data.hasOwnProperty('queries'))
        obj.queries = ApiClient.convertToType(data['queries'], {'String': 'String'});
      if (data.hasOwnProperty('relations'))
        obj.relations = ApiClient.convertToType(data['relations'], [DataRelation]);
      if (data.hasOwnProperty('reportName'))
        obj.reportName = ApiClient.convertToType(data['reportName'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = Language.constructFromObject(data['language']);
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = DataSet.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * The report parameters
 * @member {Object.<String, String>} parameters
 */
ReportResponse.prototype.parameters = undefined;

/**
 * The report queries, key is the query name and value the api operation name
 * @member {Object.<String, String>} queries
 */
ReportResponse.prototype.queries = undefined;

/**
 * The report data relations, based on the queries
 * @member {Array.<module:model/DataRelation>} relations
 */
ReportResponse.prototype.relations = undefined;

/**
 * The report name
 * @member {String} reportName
 */
ReportResponse.prototype.reportName = undefined;

/**
 * @member {module:model/Language} language
 */
ReportResponse.prototype.language = undefined;

/**
 * The report user identifier
 * @member {String} user
 */
ReportResponse.prototype.user = undefined;

/**
 * @member {module:model/DataSet} result
 */
ReportResponse.prototype.result = undefined;

