/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */

/**
 * Enum class ReportParameterType.
 * @enum {String}
 * @readonly
 */
const ReportParameterType = {
  /**
   * value: "Value"
   * @const
   */
  value: "Value",

  /**
   * value: "Now"
   * @const
   */
  now: "Now",

  /**
   * value: "Today"
   * @const
   */
  today: "Today",

  /**
   * value: "TenantId"
   * @const
   */
  tenantId: "TenantId",

  /**
   * value: "UserId"
   * @const
   */
  userId: "UserId",

  /**
   * value: "EmployeeId"
   * @const
   */
  employeeId: "EmployeeId",

  /**
   * value: "RegulationId"
   * @const
   */
  regulationId: "RegulationId",

  /**
   * value: "PayrollId"
   * @const
   */
  payrollId: "PayrollId",

  /**
   * value: "PayrunId"
   * @const
   */
  payrunId: "PayrunId",

  /**
   * value: "ReportId"
   * @const
   */
  reportId: "ReportId",

  /**
   * value: "WebhookId"
   * @const
   */
  webhookId: "WebhookId",

  /**
   * Returns a <code>ReportParameterType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ReportParameterType} The enum <code>ReportParameterType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ReportParameterType};