/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';

/**
 * The RetroPayrunJob model module.
 * @module model/RetroPayrunJob
 * @version 1
 */
export class RetroPayrunJob {
  /**
   * Constructs a new <code>RetroPayrunJob</code>.
   * The retro payrun job API object
   * @alias module:model/RetroPayrunJob
   * @class
   * @param scheduleDate {Date} The schedule date
   */
  constructor(scheduleDate) {
    this.scheduleDate = scheduleDate;
  }

  /**
   * Constructs a <code>RetroPayrunJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetroPayrunJob} obj Optional instance to populate.
   * @return {module:model/RetroPayrunJob} The populated <code>RetroPayrunJob</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RetroPayrunJob();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('scheduleDate'))
        obj.scheduleDate = ApiClient.convertToType(data['scheduleDate'], 'Date');
      if (data.hasOwnProperty('resultTags'))
        obj.resultTags = ApiClient.convertToType(data['resultTags'], ['String']);
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
RetroPayrunJob.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
RetroPayrunJob.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
RetroPayrunJob.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
RetroPayrunJob.prototype.updated = undefined;

/**
 * The schedule date
 * @member {Date} scheduleDate
 */
RetroPayrunJob.prototype.scheduleDate = undefined;

/**
 * The result tags
 * @member {Array.<String>} resultTags
 */
RetroPayrunJob.prototype.resultTags = undefined;

