/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {IntPtr} from './IntPtr';

/**
 * The RuntimeTypeHandle model module.
 * @module model/RuntimeTypeHandle
 * @version 1
 */
export class RuntimeTypeHandle {
  /**
   * Constructs a new <code>RuntimeTypeHandle</code>.
   * @alias module:model/RuntimeTypeHandle
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RuntimeTypeHandle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RuntimeTypeHandle} obj Optional instance to populate.
   * @return {module:model/RuntimeTypeHandle} The populated <code>RuntimeTypeHandle</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RuntimeTypeHandle();
      if (data.hasOwnProperty('value'))
        obj.value = IntPtr.constructFromObject(data['value']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IntPtr} value
 */
RuntimeTypeHandle.prototype.value = undefined;

