/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {CalendarConfiguration} from './CalendarConfiguration';
import {ObjectStatus} from './ObjectStatus';

/**
 * The Tenant model module.
 * @module model/Tenant
 * @version 1
 */
export class Tenant {
  /**
   * Constructs a new <code>Tenant</code>.
   * The tenant API object
   * @alias module:model/Tenant
   * @class
   * @param identifier {String} The unique identifier of the tenant (immutable)
   */
  constructor(identifier) {
    this.identifier = identifier;
  }

  /**
   * Constructs a <code>Tenant</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tenant} obj Optional instance to populate.
   * @return {module:model/Tenant} The populated <code>Tenant</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tenant();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('identifier'))
        obj.identifier = ApiClient.convertToType(data['identifier'], 'String');
      if (data.hasOwnProperty('culture'))
        obj.culture = ApiClient.convertToType(data['culture'], 'String');
      if (data.hasOwnProperty('calendar'))
        obj.calendar = CalendarConfiguration.constructFromObject(data['calendar']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
Tenant.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
Tenant.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
Tenant.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
Tenant.prototype.updated = undefined;

/**
 * The unique identifier of the tenant (immutable)
 * @member {String} identifier
 */
Tenant.prototype.identifier = undefined;

/**
 * The culture including the calendar
 * @member {String} culture
 */
Tenant.prototype.culture = undefined;

/**
 * @member {module:model/CalendarConfiguration} calendar
 */
Tenant.prototype.calendar = undefined;

/**
 * Custom attributes
 * @member {Object.<String, Object>} attributes
 */
Tenant.prototype.attributes = undefined;

