/*
 * Swagger Payroll API - OpenAPI 3.0
 * This is a base Payrolling API Gateway Server based on Ason Backend.  Some useful links: - [Ason portal](http://ason.ch/)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: mikolaj.sienko@esgroup.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';

/**
 * Enum class ValueType.
 * @enum {String}
 * @readonly
 */
const ValueType = {
  /**
   * value: "String"
   * @const
   */
  _string: "String",

  /**
   * value: "Boolean"
   * @const
   */
  _boolean: "Boolean",

  /**
   * value: "Integer"
   * @const
   */
  integer: "Integer",

  /**
   * value: "Dropdown"
   * @const
   */
  dropdown: "Dropdown",

  /**
   * value: "NumericBoolean"
   * @const
   */
  numericBoolean: "NumericBoolean",

  /**
   * value: "Decimal"
   * @const
   */
  decimal: "Decimal",

  /**
   * value: "DateTime"
   * @const
   */
  dateTime: "DateTime",

  /**
   * value: "None"
   * @const
   */
  none: "None",

  /**
   * value: "Date"
   * @const
   */
  _date: "Date",

  /**
   * value: "WebResource"
   * @const
   */
  webResource: "WebResource",

  /**
   * value: "Money"
   * @const
   */
  money: "Money",

  /**
   * value: "Percent"
   * @const
   */
  percent: "Percent",

  /**
   * value: "Hour"
   * @const
   */
  hour: "Hour",

  /**
   * value: "Day"
   * @const
   */
  day: "Day",

  /**
   * value: "Week"
   * @const
   */
  week: "Week",

  /**
   * value: "Month"
   * @const
   */
  month: "Month",

  /**
   * value: "Year"
   * @const
   */
  year: "Year",

  /**
   * value: "Distance"
   * @const
   */
  distance: "Distance",

  /**
   * Returns a <code>ValueType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ValueType} The enum <code>ValueType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ValueType};