/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';
import {ValueType} from './ValueType';

/**
 * The WageTypeCustomResult model module.
 * @module model/WageTypeCustomResult
 * @version 1
 */
export class WageTypeCustomResult {
  /**
   * Constructs a new <code>WageTypeCustomResult</code>.
   * The wage type custom result API object
   * @alias module:model/WageTypeCustomResult
   * @class
   * @param wageTypeNumber {Number} The wage type number (immutable)
   * @param source {String} The value source (immutable)
   * @param value {Number} The wage type custom result value (immutable)
   * @param start {Date} The period starting date for the value
   * @param end {Date} The period ending date for the value
   */
  constructor(wageTypeNumber, source, value, start, end) {
    this.wageTypeNumber = wageTypeNumber;
    this.source = source;
    this.value = value;
    this.start = start;
    this.end = end;
  }

  /**
   * Constructs a <code>WageTypeCustomResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WageTypeCustomResult} obj Optional instance to populate.
   * @return {module:model/WageTypeCustomResult} The populated <code>WageTypeCustomResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WageTypeCustomResult();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('wageTypeResultId'))
        obj.wageTypeResultId = ApiClient.convertToType(data['wageTypeResultId'], 'Number');
      if (data.hasOwnProperty('wageTypeNumber'))
        obj.wageTypeNumber = ApiClient.convertToType(data['wageTypeNumber'], 'Number');
      if (data.hasOwnProperty('wageTypeName'))
        obj.wageTypeName = ApiClient.convertToType(data['wageTypeName'], 'String');
      if (data.hasOwnProperty('wageTypeNameLocalizations'))
        obj.wageTypeNameLocalizations = ApiClient.convertToType(data['wageTypeNameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('valueType'))
        obj.valueType = ValueType.constructFromObject(data['valueType']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
WageTypeCustomResult.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
WageTypeCustomResult.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
WageTypeCustomResult.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
WageTypeCustomResult.prototype.updated = undefined;

/**
 * The wage type result id (immutable)
 * @member {Number} wageTypeResultId
 */
WageTypeCustomResult.prototype.wageTypeResultId = undefined;

/**
 * The wage type number (immutable)
 * @member {Number} wageTypeNumber
 */
WageTypeCustomResult.prototype.wageTypeNumber = undefined;

/**
 * The wage type name (immutable)
 * @member {String} wageTypeName
 */
WageTypeCustomResult.prototype.wageTypeName = undefined;

/**
 * The localized wage type names (immutable)
 * @member {Object.<String, String>} wageTypeNameLocalizations
 */
WageTypeCustomResult.prototype.wageTypeNameLocalizations = undefined;

/**
 * The value source (immutable)
 * @member {String} source
 */
WageTypeCustomResult.prototype.source = undefined;

/**
 * @member {module:model/ValueType} valueType
 */
WageTypeCustomResult.prototype.valueType = undefined;

/**
 * The wage type custom result value (immutable)
 * @member {Number} value
 */
WageTypeCustomResult.prototype.value = undefined;

/**
 * The period starting date for the value
 * @member {Date} start
 */
WageTypeCustomResult.prototype.start = undefined;

/**
 * The period ending date for the value
 * @member {Date} end
 */
WageTypeCustomResult.prototype.end = undefined;

/**
 * The result tags
 * @member {Array.<String>} tags
 */
WageTypeCustomResult.prototype.tags = undefined;

/**
 * The result attributes (immutable)
 * @member {Object.<String, Object>} attributes
 */
WageTypeCustomResult.prototype.attributes = undefined;

