/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../api/ApiClient';
import {CalendarCalculationMode} from './CalendarCalculationMode';
import {ObjectStatus} from './ObjectStatus';
import {OverrideType} from './OverrideType';
import {ValueType} from './ValueType';

/**
 * The WageType model module.
 * @module model/WageType
 * @version 1
 */
export class WageType {
  /**
   * Constructs a new <code>WageType</code>.
   * The regulation wage type API object
   * @alias module:model/WageType
   * @class
   * @param wageTypeNumber {Number} The wage type number (immutable)
   * @param name {String} The wage type name
   */
  constructor(wageTypeNumber, name) {
    this.wageTypeNumber = wageTypeNumber;
    this.name = name;
  }

  /**
   * Constructs a <code>WageType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WageType} obj Optional instance to populate.
   * @return {module:model/WageType} The populated <code>WageType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WageType();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('wageTypeNumber'))
        obj.wageTypeNumber = ApiClient.convertToType(data['wageTypeNumber'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('nameLocalizations'))
        obj.nameLocalizations = ApiClient.convertToType(data['nameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('descriptionLocalizations'))
        obj.descriptionLocalizations = ApiClient.convertToType(data['descriptionLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('overrideType'))
        obj.overrideType = OverrideType.constructFromObject(data['overrideType']);
      if (data.hasOwnProperty('valueType'))
        obj.valueType = ValueType.constructFromObject(data['valueType']);
      if (data.hasOwnProperty('calendarCalculationMode'))
        obj.calendarCalculationMode = CalendarCalculationMode.constructFromObject(data['calendarCalculationMode']);
      if (data.hasOwnProperty('collectors'))
        obj.collectors = ApiClient.convertToType(data['collectors'], ['String']);
      if (data.hasOwnProperty('collectorGroups'))
        obj.collectorGroups = ApiClient.convertToType(data['collectorGroups'], ['String']);
      if (data.hasOwnProperty('valueExpression'))
        obj.valueExpression = ApiClient.convertToType(data['valueExpression'], 'String');
      if (data.hasOwnProperty('resultExpression'))
        obj.resultExpression = ApiClient.convertToType(data['resultExpression'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
      if (data.hasOwnProperty('clusters'))
        obj.clusters = ApiClient.convertToType(data['clusters'], ['String']);
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
WageType.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
WageType.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
WageType.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
WageType.prototype.updated = undefined;

/**
 * The wage type number (immutable)
 * @member {Number} wageTypeNumber
 */
WageType.prototype.wageTypeNumber = undefined;

/**
 * The wage type name
 * @member {String} name
 */
WageType.prototype.name = undefined;

/**
 * The localized wage type names
 * @member {Object.<String, String>} nameLocalizations
 */
WageType.prototype.nameLocalizations = undefined;

/**
 * The wage type description
 * @member {String} description
 */
WageType.prototype.description = undefined;

/**
 * The localized wage type descriptions
 * @member {Object.<String, String>} descriptionLocalizations
 */
WageType.prototype.descriptionLocalizations = undefined;

/**
 * @member {module:model/OverrideType} overrideType
 */
WageType.prototype.overrideType = undefined;

/**
 * @member {module:model/ValueType} valueType
 */
WageType.prototype.valueType = undefined;

/**
 * @member {module:model/CalendarCalculationMode} calendarCalculationMode
 */
WageType.prototype.calendarCalculationMode = undefined;

/**
 * Associated collectors
 * @member {Array.<String>} collectors
 */
WageType.prototype.collectors = undefined;

/**
 * Associated collector groups
 * @member {Array.<String>} collectorGroups
 */
WageType.prototype.collectorGroups = undefined;

/**
 * Expression: calculates of the wage type value
 * @member {String} valueExpression
 */
WageType.prototype.valueExpression = undefined;

/**
 * Expression: calculates of the wage type result attributes
 * @member {String} resultExpression
 */
WageType.prototype.resultExpression = undefined;

/**
 * Custom attributes
 * @member {Object.<String, Object>} attributes
 */
WageType.prototype.attributes = undefined;

/**
 * The wage type clusters
 * @member {Array.<String>} clusters
 */
WageType.prototype.clusters = undefined;

