/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';
import {ValueType} from './ValueType';
import {WageTypeCustomResult} from './WageTypeCustomResult';

/**
 * The WageTypeResultSet model module.
 * @module model/WageTypeResultSet
 * @version 1
 */
export class WageTypeResultSet {
  /**
   * Constructs a new <code>WageTypeResultSet</code>.
   * The wage type result set API object
   * @alias module:model/WageTypeResultSet
   * @class
   * @param wageTypeId {Number} The wage type id (immutable)
   * @param wageTypeNumber {Number} The wage type number (immutable)
   * @param wageTypeName {String} The wage type name (immutable)
   * @param value {Number} The wage type result value (immutable)
   * @param start {Date} The starting date for the value
   * @param end {Date} The ending date for the value
   */
  constructor(wageTypeId, wageTypeNumber, wageTypeName, value, start, end) {
    this.wageTypeId = wageTypeId;
    this.wageTypeNumber = wageTypeNumber;
    this.wageTypeName = wageTypeName;
    this.value = value;
    this.start = start;
    this.end = end;
  }

  /**
   * Constructs a <code>WageTypeResultSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WageTypeResultSet} obj Optional instance to populate.
   * @return {module:model/WageTypeResultSet} The populated <code>WageTypeResultSet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WageTypeResultSet();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('payrollResultId'))
        obj.payrollResultId = ApiClient.convertToType(data['payrollResultId'], 'Number');
      if (data.hasOwnProperty('wageTypeId'))
        obj.wageTypeId = ApiClient.convertToType(data['wageTypeId'], 'Number');
      if (data.hasOwnProperty('wageTypeNumber'))
        obj.wageTypeNumber = ApiClient.convertToType(data['wageTypeNumber'], 'Number');
      if (data.hasOwnProperty('wageTypeName'))
        obj.wageTypeName = ApiClient.convertToType(data['wageTypeName'], 'String');
      if (data.hasOwnProperty('wageTypeNameLocalizations'))
        obj.wageTypeNameLocalizations = ApiClient.convertToType(data['wageTypeNameLocalizations'], {'String': 'String'});
      if (data.hasOwnProperty('valueType'))
        obj.valueType = ValueType.constructFromObject(data['valueType']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
      if (data.hasOwnProperty('customResults'))
        obj.customResults = ApiClient.convertToType(data['customResults'], [WageTypeCustomResult]);
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
WageTypeResultSet.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
WageTypeResultSet.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
WageTypeResultSet.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
WageTypeResultSet.prototype.updated = undefined;

/**
 * The payroll result id (immutable)
 * @member {Number} payrollResultId
 */
WageTypeResultSet.prototype.payrollResultId = undefined;

/**
 * The wage type id (immutable)
 * @member {Number} wageTypeId
 */
WageTypeResultSet.prototype.wageTypeId = undefined;

/**
 * The wage type number (immutable)
 * @member {Number} wageTypeNumber
 */
WageTypeResultSet.prototype.wageTypeNumber = undefined;

/**
 * The wage type name (immutable)
 * @member {String} wageTypeName
 */
WageTypeResultSet.prototype.wageTypeName = undefined;

/**
 * The localized wage type names (immutable)
 * @member {Object.<String, String>} wageTypeNameLocalizations
 */
WageTypeResultSet.prototype.wageTypeNameLocalizations = undefined;

/**
 * @member {module:model/ValueType} valueType
 */
WageTypeResultSet.prototype.valueType = undefined;

/**
 * The wage type result value (immutable)
 * @member {Number} value
 */
WageTypeResultSet.prototype.value = undefined;

/**
 * The starting date for the value
 * @member {Date} start
 */
WageTypeResultSet.prototype.start = undefined;

/**
 * The ending date for the value
 * @member {Date} end
 */
WageTypeResultSet.prototype.end = undefined;

/**
 * The result tags
 * @member {Array.<String>} tags
 */
WageTypeResultSet.prototype.tags = undefined;

/**
 * The result attributes (immutable)
 * @member {Object.<String, Object>} attributes
 */
WageTypeResultSet.prototype.attributes = undefined;

/**
 * The wage type custom results (immutable)
 * @member {Array.<module:model/WageTypeCustomResult>} customResults
 */
WageTypeResultSet.prototype.customResults = undefined;

