/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';

/**
 * The WebhookMessage model module.
 * @module model/WebhookMessage
 * @version 1
 */
export class WebhookMessage {
  /**
   * Constructs a new <code>WebhookMessage</code>.
   * The Webhook message API object
   * @alias module:model/WebhookMessage
   * @class
   * @param actionName {String} The webhook action name
   * @param receiverAddress {String} The webhook receiver address
   * @param requestDate {Date} The request date
   */
  constructor(actionName, receiverAddress, requestDate) {
    this.actionName = actionName;
    this.receiverAddress = receiverAddress;
    this.requestDate = requestDate;
  }

  /**
   * Constructs a <code>WebhookMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookMessage} obj Optional instance to populate.
   * @return {module:model/WebhookMessage} The populated <code>WebhookMessage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebhookMessage();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('actionName'))
        obj.actionName = ApiClient.convertToType(data['actionName'], 'String');
      if (data.hasOwnProperty('receiverAddress'))
        obj.receiverAddress = ApiClient.convertToType(data['receiverAddress'], 'String');
      if (data.hasOwnProperty('requestDate'))
        obj.requestDate = ApiClient.convertToType(data['requestDate'], 'Date');
      if (data.hasOwnProperty('requestMessage'))
        obj.requestMessage = ApiClient.convertToType(data['requestMessage'], 'String');
      if (data.hasOwnProperty('requestOperation'))
        obj.requestOperation = ApiClient.convertToType(data['requestOperation'], 'String');
      if (data.hasOwnProperty('responseDate'))
        obj.responseDate = ApiClient.convertToType(data['responseDate'], 'Date');
      if (data.hasOwnProperty('responseStatus'))
        obj.responseStatus = ApiClient.convertToType(data['responseStatus'], 'Number');
      if (data.hasOwnProperty('responseMessage'))
        obj.responseMessage = ApiClient.convertToType(data['responseMessage'], 'String');
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
WebhookMessage.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
WebhookMessage.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
WebhookMessage.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
WebhookMessage.prototype.updated = undefined;

/**
 * The webhook action name
 * @member {String} actionName
 */
WebhookMessage.prototype.actionName = undefined;

/**
 * The webhook receiver address
 * @member {String} receiverAddress
 */
WebhookMessage.prototype.receiverAddress = undefined;

/**
 * The request date
 * @member {Date} requestDate
 */
WebhookMessage.prototype.requestDate = undefined;

/**
 * The request message
 * @member {String} requestMessage
 */
WebhookMessage.prototype.requestMessage = undefined;

/**
 * The request operation
 * @member {String} requestOperation
 */
WebhookMessage.prototype.requestOperation = undefined;

/**
 * The response date
 * @member {Date} responseDate
 */
WebhookMessage.prototype.responseDate = undefined;

/**
 * The response HTTP status code
 * @member {Number} responseStatus
 */
WebhookMessage.prototype.responseStatus = undefined;

/**
 * The response message
 * @member {String} responseMessage
 */
WebhookMessage.prototype.responseMessage = undefined;

