/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ObjectStatus} from './ObjectStatus';
import {WebhookAction} from './WebhookAction';

/**
 * The Webhook model module.
 * @module model/Webhook
 * @version 1
 */
export class Webhook {
  /**
   * Constructs a new <code>Webhook</code>.
   * The Webhook API object
   * @alias module:model/Webhook
   * @class
   * @param name {String} The payroll name
   * @param receiverAddress {String} The webhook receiver address
   * @param action {module:model/WebhookAction} 
   */
  constructor(name, receiverAddress, action) {
    this.name = name;
    this.receiverAddress = receiverAddress;
    this.action = action;
  }

  /**
   * Constructs a <code>Webhook</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Webhook} obj Optional instance to populate.
   * @return {module:model/Webhook} The populated <code>Webhook</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Webhook();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ObjectStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('receiverAddress'))
        obj.receiverAddress = ApiClient.convertToType(data['receiverAddress'], 'String');
      if (data.hasOwnProperty('action'))
        obj.action = WebhookAction.constructFromObject(data['action']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], {'String': Object});
    }
    return obj;
  }
}

/**
 * The unique object id (immutable)
 * @member {Number} id
 */
Webhook.prototype.id = undefined;

/**
 * @member {module:model/ObjectStatus} status
 */
Webhook.prototype.status = undefined;

/**
 * The date which the API object was created (immutable)
 * @member {Date} created
 */
Webhook.prototype.created = undefined;

/**
 * The date which the API object was last updated (immutable)
 * @member {Date} updated
 */
Webhook.prototype.updated = undefined;

/**
 * The payroll name
 * @member {String} name
 */
Webhook.prototype.name = undefined;

/**
 * The webhook receiver address
 * @member {String} receiverAddress
 */
Webhook.prototype.receiverAddress = undefined;

/**
 * @member {module:model/WebhookAction} action
 */
Webhook.prototype.action = undefined;

/**
 * Custom attributes
 * @member {Object.<String, Object>} attributes
 */
Webhook.prototype.attributes = undefined;

