/*
 * Ason Payroll Integration API v1
 * Integration API for the system provider [<a target=\"_blank\" href='https://ason.ch'>v0.3.0-pre-230213</a>]
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class WebhookAction.
 * @enum {String}
 * @readonly
 */
const WebhookAction = {
  /**
   * value: "None"
   * @const
   */
  none: "None",

  /**
   * value: "CaseFunctionRequest"
   * @const
   */
  caseFunctionRequest: "CaseFunctionRequest",

  /**
   * value: "CaseChangeAdded"
   * @const
   */
  caseChangeAdded: "CaseChangeAdded",

  /**
   * value: "PayrunFunctionRequest"
   * @const
   */
  payrunFunctionRequest: "PayrunFunctionRequest",

  /**
   * value: "PayrunJobProcess"
   * @const
   */
  payrunJobProcess: "PayrunJobProcess",

  /**
   * value: "PayrunJobFinish"
   * @const
   */
  payrunJobFinish: "PayrunJobFinish",

  /**
   * value: "ReportFunctionRequest"
   * @const
   */
  reportFunctionRequest: "ReportFunctionRequest",

  /**
   * value: "TaskChange"
   * @const
   */
  taskChange: "TaskChange",

  /**
   * Returns a <code>WebhookAction</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/WebhookAction} The enum <code>WebhookAction</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {WebhookAction};