name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_build_command: "npm run build"
          app_location: "/"
          api_location: "api"
          output_location: "build"
          # deployment_environment: ${{!inputs.production && 'staging' || null }}
        env:
          VITE_AUTHORITY_URL: "https://login.asonpayroll.com"
          VITE_AUTHORITY_SETTINGS_URL: "https://login.asonpayroll.com/ui/console/"
          VITE_API_URL: ${{ vars.API_URL }}
          VITE_REDIRECT_URL: ${{ vars.REDIRECT_URL }}
          VITE_PROJECT_ID: ${{ vars.PROJECT_ID }}
          VITE_CLIENT_ID: ${{ vars.CLIENT_ID }}
          VITE_APP_NAME: "Ason Payroll"
          VITE_META_DESCRIPTION: "Ason Global Payroll Service Portal."
